backend:
  name: git-gateway 
  branch: main # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
display_url: https://your-site.com
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_files/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: 'Title', name: 'title', widget: 'string', required: true},
      - {label: 'Subtitle', name: 'subtitle', widget: 'markdown', required: false},
      - {label: 'Text', name: 'text', widget: 'markdown', required: false},
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: 'Images block', 
        name: 'imagesBlock', 
        widget: 'list', 
        required: false, 
        collapsed: false,
        fields: 
          - { label: 'Disposition', name: 'disposition', widget: 'select', options: ['line', 'square', 'normal']}
          - label: 'Images', 
            name: 'images', 
            widget: 'list', 
            allow_multiple: false, 
            required: false, 
            collapsed: false,
            fields: 
              - {label: 'Image', name: 'image', widget: 'image', required: true},
              - {label: 'Image Alt', name: 'imageAlt', widget: 'string', required: false},
              - {label: 'Description', name: 'description', widget: 'markdown', required: false}